apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: wxza4quho-python 
  janus-idp.io/tekton: wxza4quho-python
  backstage.io/kubernetes-id: wxza4quho-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wxza4quho-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml