apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wxza4quho-python
  janus-idp.io/tekton: wxza4quho-python
  backstage.io/kubernetes-id: wxza4quho-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wxza4quho-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
