apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: wxza4quho-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wxza4quho-python 
  name: wxza4quho-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: wxza4quho-python
    weight: 100 
