apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wxza4quho-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:c126c8ce45185fb9ca476ef6a740960bf4a58a83@sha256:61f6073942a514ad09ef5e6afaaa0e718a1fb1fed6d60c0740367d75576c128e
          name: container-image
